---
- name: loop playbook
  hosts: localhost
  become: yes
  tasks:
     - name: install multiple
       yum:
         name: "{{item.a}}"
         state: "{{item.b}}"       
       with_items:
         - {a: httpd, b: latest}
         - {a: git, b: latest}
         - {a: tree, b: absent}
           
     - name: start httpd
       service:
          name: "{{item.a}}"
          state: "{{item.c}}"
       with_items:     
         - {a: httpd, c: started}   
